-- MySQL Script generated by MySQL Workbench
-- 11/10/15 17:06:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ksiazka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ksiazka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ksiazka` (
  `idKsiazka` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `autor` VARCHAR(45) NOT NULL COMMENT '',
  `tytul` VARCHAR(45) NOT NULL COMMENT '',
  `cena` FLOAT NOT NULL COMMENT '',
  `dict_img` VARCHAR(120) NOT NULL COMMENT '',
  `kategoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idKsiazka`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Koszyk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Koszyk` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Koszyk` (
  `idKoszyk` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `wart_Kosz` FLOAT NULL COMMENT '',
  `ilosc_Ksiaz` INT NULL COMMENT '',
  `zmienna_ses_kosz` INT NOT NULL COMMENT '',
  `status` SMALLINT(6) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`idKoszyk`)  COMMENT '',
  UNIQUE INDEX `zmienna_ses_UNIQUE` (`zmienna_ses_kosz` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listaKoszyka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`listaKoszyka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`listaKoszyka` (
  `idKsiazek` INT NOT NULL COMMENT '',
  `idKoszyka` INT NOT NULL COMMENT '',
  `ilość` INT NOT NULL COMMENT '',
  INDEX `idKsiazek_idx` (`idKsiazek` ASC)  COMMENT '',
  INDEX `idKoszyka_idx` (`idKoszyka` ASC)  COMMENT '',
  CONSTRAINT `idKsiazek`
    FOREIGN KEY (`idKsiazek`)
    REFERENCES `mydb`.`Ksiazka` (`idKsiazka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKoszyka`
    FOREIGN KEY (`idKoszyka`)
    REFERENCES `mydb`.`Koszyk` (`idKoszyk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
