-- MySQL Script generated by MySQL Workbench
-- 01/12/16 11:39:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tas` ;

-- -----------------------------------------------------
-- Table `tas`.`Ksiazka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tas`.`Ksiazka` ;

CREATE TABLE IF NOT EXISTS `tas`.`Ksiazka` (
  `idKsiazka` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `autor` VARCHAR(45) NOT NULL COMMENT '',
  `tytul` VARCHAR(45) NOT NULL COMMENT '',
  `cena` FLOAT NOT NULL COMMENT '',
  `dict_img` VARCHAR(120) NOT NULL COMMENT '',
  `kategoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idKsiazka`)  COMMENT '',
  UNIQUE INDEX `idKsiazka_UNIQUE` (`idKsiazka` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tas`.`Uzytkownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tas`.`Uzytkownik` ;

CREATE TABLE IF NOT EXISTS `tas`.`Uzytkownik` (
  `idUzytkownik` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NOT NULL COMMENT '',
  `haslo` VARCHAR(64) NOT NULL COMMENT '',
  `adres` VARCHAR(45) NOT NULL COMMENT '',
  `nr_telefonu` INT(16) NULL COMMENT '',
  `email` VARCHAR(256) NULL COMMENT '',
  PRIMARY KEY (`idUzytkownik`)  COMMENT '',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  COMMENT '',
  UNIQUE INDEX `idUzytkownik_UNIQUE` (`idUzytkownik` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tas`.`Koszyk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tas`.`Koszyk` ;

CREATE TABLE IF NOT EXISTS `tas`.`Koszyk` (
  `idKoszyk` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idUzytkownik` INT NOT NULL COMMENT '',
  `data_realizacji` DATETIME NULL COMMENT '',
  `zmienna_ses_kosz` INT NOT NULL COMMENT '',
  `status_zamowienia` SMALLINT(6) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`idKoszyk`)  COMMENT '',
  UNIQUE INDEX `zmienna_ses_UNIQUE` (`zmienna_ses_kosz` ASC)  COMMENT '',
  INDEX `fk_Koszyk_Uzytkownik3_idx` (`idUzytkownik` ASC)  COMMENT '',
  UNIQUE INDEX `idKoszyk_UNIQUE` (`idKoszyk` ASC)  COMMENT '',
  CONSTRAINT `fk_Koszyk_Uzytkownik3`
    FOREIGN KEY (`idUzytkownik`)
    REFERENCES `tas`.`Uzytkownik` (`idUzytkownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tas`.`listaKoszyka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tas`.`listaKoszyka` ;

CREATE TABLE IF NOT EXISTS `tas`.`listaKoszyka` (
  `idKsiazek` INT NOT NULL COMMENT '',
  `idKoszyka` INT NOT NULL COMMENT '',
  `ilość` INT NOT NULL COMMENT '',
  INDEX `idKsiazek_idx` (`idKsiazek` ASC)  COMMENT '',
  INDEX `idKoszyka_idx` (`idKoszyka` ASC)  COMMENT '',
  PRIMARY KEY (`idKsiazek`, `idKoszyka`)  COMMENT '',
  CONSTRAINT `idKsiazek`
    FOREIGN KEY (`idKsiazek`)
    REFERENCES `tas`.`Ksiazka` (`idKsiazka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKoszyka`
    FOREIGN KEY (`idKoszyka`)
    REFERENCES `tas`.`Koszyk` (`idKoszyk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tas`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tas`.`Tag` ;

CREATE TABLE IF NOT EXISTS `tas`.`Tag` (
  `nazwaTagu` INT NOT NULL COMMENT '',
  PRIMARY KEY (`nazwaTagu`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tas`.`listaTagu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tas`.`listaTagu` ;

CREATE TABLE IF NOT EXISTS `tas`.`listaTagu` (
  `nazwaTagu` INT NOT NULL COMMENT '',
  `Ksiazka_idKsiazka` INT NOT NULL COMMENT '',
  INDEX `fk_listaTagu_Tag1_idx` (`nazwaTagu` ASC)  COMMENT '',
  PRIMARY KEY (`nazwaTagu`, `Ksiazka_idKsiazka`)  COMMENT '',
  INDEX `fk_listaTagu_Ksiazka1_idx` (`Ksiazka_idKsiazka` ASC)  COMMENT '',
  CONSTRAINT `fk_listaTagu_Tag1`
    FOREIGN KEY (`nazwaTagu`)
    REFERENCES `tas`.`Tag` (`nazwaTagu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listaTagu_Ksiazka1`
    FOREIGN KEY (`Ksiazka_idKsiazka`)
    REFERENCES `tas`.`Ksiazka` (`idKsiazka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
